name: Display repository size
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest.
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: .
      - run: |
          echo "${{ github.branch.base_ref }}"
          du skh--exclude=".git"